---
title: IDEMA Fall 2020 - Course Introduction 
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---

```{r, echo = FALSE}
library(emo)
```

# Introduction

Welcome to **Infectious Disease Epidemiology - a Model-based Approach**. This is a long title, so I'll be referring to the course as IDEMA for short.


# Module Overview
The course is divided into modules. Each module consists of one or several units. This first module provides a brief introduction to the course, followed by discussing and setting up our various tools. 

# Module Learning Objectives
The specific learning objectives for this module are:

* Know what this course is all about.
* Know how this course is set up and what you are expected to do.
* Have all course tools and software set up and running.
*	Get to know the instructor and your fellow students.


# Course Learning Objectives 

The main goal for this course is for you to learn different concepts of infectious disease (ID) epidemiology from a model-based perspective. 

I hope that this course will provide you with a view of infectious diseases at the population level (i.e. infectious disease epidemiology), which complements both a clinical perspective based on individual patients, and a classical epidemiological perspective based on specific study groups and designs (e.g. case-control, cohort and similar studies). 

Throughout this course, We will take a systems perspective to understand spread and control of infectious diseases. 

To give an example: We know that many infectious diseases have temporal patterns. E.g. influenza outbreaks usually occur annually, while measles outbreaks -- before widespread vaccination -- often occurred in multi-year cycles. What determines such patterns? The classical medical and epidemiological approaches are not well suited to answer this question, but - as we will see in this course - a systems perspective using models as tools for inquiry can answer this and other questions related to population level disease patterns.

The learning objectives listed here are not complete, but cover the significant aspects of the course. By the end of the course, you will be able to:

* Explain and compute important epidemiological measures, such as reproductive number and level of herd immunity
* Appraise the fundamentally causal nature of mechanistic infectious disease (ID) computer models and master the use of such models to address important ID epidemiology research questions
* Interpret the meaning of specific dynamic patterns seen in ID incidence and prevalence
* Choose optimal ID intervention strategies based on features of specific IDs
* Predict the impact of different ID intervention strategies
* Critically evaluate the ID epidemiology literature
* Compare and assess the strengths and weaknesses of different ID data collection and analysis approaches
* Formulate meaningful ID epidemiology research questions of public health importance 
* Select the appropriate data collection and analysis approach for a specific ID research question
* Explain the importance of system dynamical thinking for the study and control of ID



# Course Prerequisites

While the course is all about infectious diseases (ID), we will not spend much time discussing different diseases in detail. Instead, the focus is on overall patterns we see among different types of ID. We will of course often use specific ID as an example. In that case, I assume you know some basics of the disease or if you do not, that you will be reading up on it. Knowledge about a specific ID at the level provided by sources such as Wikipedia or CDC is usually enough.

I also assume that you are familiar with public health/epidemiology concepts and terminology at a basic level. If you come across concepts or terms that you are unfamiliar with, a quick online search should help fill any gaps.

The study of infectious diseases as dynamical systems is intimately linked to mathematical and computational modeling of infectious diseases. For that reason, this course has a computational component. To reduce the barriers surrounding computational modeling, the course does not require any programming on your part. In this course, we will learn how to use ID computer models, but not how to formulate models and write computer programs of those models. Instead, you will be interactively exploring already developed computer simulations of infectious disease systems. So while there will be computer simulations, and you will see equations describing the computer models, this course does not require you to know any programming or to perform any mathematical manipulations beyond basic algebra.



# Course Philosophy

I describe my thoughts on teaching and learning a bit more in the __completely optional__ _Teaching and Learning thoughts_ document, which is part of this module. As a summary, here are my goals, promises, and expectations for this course.

* I expect you to be self-motivated and committed to learning the material by putting in the effort needed to succeed.

* I will try to maximize the rewards you get by hopefully teaching topics you find interesting and useful.

* This class strives to be challenging but non-threatening. As such, you will be asked to work hard, and I expect you to do the assigned tasks by the deadlines, but in the end, I usually don't grade hard - unless you fail to keep up your end of the agreement and don't put in the work.

* This class is 'open everything'. You can use the internet, ask your classmates, myself and others, get help from wherever you can. I trust you will find the right balance of getting help when you need it while still putting in enough effort to experience real learning. 

* I will not perform any 'policing' to try to prevent you from taking shortcuts (i.e., not doing work yourself). The class contains graded assessments with deadlines, but those are meant to _help you stay on track._ If you cheat - and cheating will be easy - you are mainly cheating yourself out of learning. 


__Overall, I hope this course is going to be useful, interesting, challenging and also interactive. Online courses are always a bit tricky with interaction/participation. I hope we can create something online that feels like a classroom. Please participate, ask questions, provide feedback, make suggestions for improvements, etc. The more you engage in the course, the more you'll get out of it.__


# Course Setup
* The course is split into modules, each with one or more units. Each module will usually be covered in a week. The _Schedule_ document gives an outline. The schedule is not fully finalized and will change, so check frequently.
* Each module consists of one or several units/documents containing a mix of things I wrote, writings or videos by others, computer based exercises, discussions, etc. Content for a specific module is listed in the order you should go through things. It should always be clear what is required for a given module. If anything is ever unclear, please ask (see _Communications_ section on course website).
* All material for the course can be accessed through this course website. Most material is not yet available. It will be added/unlocked as the course proceeds.
* The main page of the course describes the different sections and documents. 

# Course Tools
This is a brief overview of the tools we will be using for this class. The next module, which you can and should start right after finishing this one, describes all these tools in more detail and gives instructions on how to set them all up.

* We will use the DSAIDE software package in this course. This software is written for R. Therefore, you will also need to install R, which is very easy. Further instructions on this are provided.
* We will also use RStudio (a graphical frontend to R).
* We will use Slack for discussions, help, announcements, and any other form of asynchronous communication.
* We will use Zoom for occasional, completely optional synchronous disucssions.


# Assessments

The grade will be made up as follows:

* 20% weekly quizzes
* 20% homework/small projects
* 20% discussion and general participation
* 40% a course long project, broken up into pieces. 

The following grading scale will be used, final grades might be curved (upward): A 93-100, A- 90-93, B+ 87-90, B 83-87, B- 80-83, C+ 77-80, C 73-77, C- 70-73, D 60-70, F < 60

Most modules have assessments (these are graded). Due dates are usually Friday 5 pm the week of the module. Some might be at other times, e.g., the beginning or middle of the week. You are responsible for keeping up with the due dates. If in doubt, ask.

Every module will have an _Assessment_ document, which describes what work you need to do for that module that will be graded. The following types of assessments are part of the course.

## Online quizzes
You will be provided with quiz sheets in the form of Excel files which contain quiz questions covering both the DSAIDE software and the course material. You can do the quizzes at any time, and need to upload your answers by the due date for a given week. The primary purpose of the quizzes is to ensure you worked through the assigned material. 

## Exercises
The exercises are part of a single module and are due on the last day of the module. They are listed in the _Schedule_ and described in more detail in the _Exercises_ section. I will likely add further ones, so look out for updates. The _Assessment_ document for each module will tell you which exercise to do.

## Class project
The project is a semester-long data analysis project broken into pieces with several deadlines. The _Projects_ section provides more details.

## Discussion and Participation
At times, I will ask you to post specific assignments to the discussion boards and reply to other posts. I also encourage general, continued participation on the discussion boards. Participation can take any form, such as asking questions, answering questions, posting links to interesting content, providing feedback, etc. The more, the better `r emo::ji('smile')`. Both quality and quantity will affect your participation grade. 

# Course Resources
We'll be drawing on a lot of different resources. I compiled a list with the ones we'll use and others you might find helpful in the _Resources_ section of the class website. 

# Getting help
I do not expect you to figure it all out yourselves. You will get stuck and are encouraged to seek help. Please use the communications tools for this class liberally to ask for help.
