---
title: Characterizing Infection States - Exercises 
subtitle: ""
author: Andreas Handel
date: "`r as.Date(file.mtime(knitr::current_input()))`"
output: 
  html_document:
    toc_depth: 3
---


```{r, include = FALSE}
#just so I can use emoticons
#devtools::install_github("hadley/emo")
library(emo)
```

# Hands-on computer exercise

For this module, work through the _Characteristics of ID_ app. Fill and submit the corresponding quiz sheet.



# Topic discussion 

Read the paper “Modelling an outbreak of an emerging pathogen” by Kajita et al (2007). You can get the paper [here](./media/kajita07natrevmic.pdf). There are likely several aspect in the paper that you won't understand yet, for instance the whole _reproductive number_ part, and others as well. That's ok, this is why you are taking this course after all `r emo::ji('smile')`. Try to understand as much as possible, skip the parts that you can't follow.

The paper lists 8 assumptions that went into constructing the model. Is there any assumption that you might have made differently, and why? Are there other assumptions the authors make when building the model that are not included in their list of assumptions? If your next step would be to further increase model realism, what would you do, i.e. what feature(s) would you include that are currently not in the model? 

Post your thoughts to the discussion channel, then respond to posts by others. The general rules for discussion and assessment apply.



