---
title: Overview of Infectious Disease Dynamics  
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---



##Overview
This module provides an introduction to the overall idea of studying the dynamics of infectious diseases, why it is useful to take a model-based approach, and what that means. 


# Assignments



* [The "Introduction to the dynamical systems approach" chapter of the DSAIDE book](https://ahgroup.github.io/DSAIDEbook). 
* The paper "Systems Science Methods in Public Health: Dynamics, Networks, and Agents" by Luke & Stamatakis (in the folder for this module).


Start by reading the ["Characterizing Infectious Disease States" chapter of the DSAIDE book](https://ahgroup.github.io/DSAIDEbook/characterizing-infectious-disease-states.html). 

The book chapter gives you one view .

For some further discussions, check out the following videos. 


###Things to read

###Videos to watch 
* See the Videos document.

_Note: For this and any future modules, you can do the videos and readings in any order. Usually, if there is a paper assigned, it is best to read it last since it often assumes knowledge of material covered in the videos and the reading._

###Computer Exercises to do
* Work through the Shiny App listed at the end of the assigned DSAIDE book chapter, i.e. read the information on all tabs inside the app and do all tasks described in the "What to do" section. 

__As you work through the apps, always take notes, write down your results as you work through the shiny app. The practice quiz for this module (and all others) will ask you about specific results you got by doing the Shiny app exercises.__ (E.g. you might be asked 'What was the number of susceptibles left at the end of the outbreak for task 3 in the shiny app for this module?').  

###Discussions to participate in
* From the exercise section of the DSAIDE book chapter for this module, answer the question that refers to the assigned paper by Luke & Stamatakis. 
* Post your answer to the exercise to the discussion forum for this module. Then comment on posts by others. The general rules for discussion and assessment as described in the first module apply.

_In addition to the tasks just described, you are welcome and encouraged to discuss anything else related to the content of this module within the topic for this module. Discuss anything else relevant to the course in the appropriate topic area._


# Overview
In this module, we will discuss how to characterize the infection states of different ID. We will look at this both from a medical perspective and from a public health perspective and discuss how these perspectives complement each other. 


# Assignments

Start by reading the ["Characterizing Infectious Disease States" chapter of IDEMAB](https://andreashandel.github.io/IDEMAbook/characterizing-infectious-disease-states.html). 

The book chapter gives you one view .

For some further discussions, check out the following videos. 

The first video is from the ["Epidemics"](https://www.coursera.org/learn/epidemics) online course. Mary Poss, one of the course instructors, talks about the difference between infection and disease.

<p><iframe width="560" height="315" src="https://www.youtube.com/embed/feurlFtWIsM" frameborder="0" allowfullscreen></iframe></p>

The second video is from the HKU Epidemics course sequence. In that video, Joseph Wu from the University of Hong Kong discusses some quantities relating to infection and disease state and duration and their importance for public health. Again, ignore anything we haven't covered yet.

<p><iframe width="560" height="315" src="https://www.youtube.com/embed/z9EItIxkaVs" frameborder="0" allowfullscreen></iframe></p>





###Videos to watch
* See Videos document

###Computer Exercises to do
* Work through the Shiny App listed at the end of the assigned DSAIDE book chapter.  

###Discussions to participate in
* From the exercise section of the DSAIDE chapter for this module, answer the question that refers to the assigned paper by Kajita et al.
* Post to the discussion forum for this module. The general rules for discussion and assessment apply.

* The Paper by Kajita et al, Nat Rev Mic 2007. When reading the paper, focus on understanding their model and assumptions. You can skim or skip anything related to the reproductive number, R~0~, for now. We'll discuss that quantity soon.


