---
title: Reproductive Number - Assessment 
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r as.Date(file.mtime(knitr::current_input()))`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---

# Module Assessments

Make sure you've gone through all the content for this module. 


## Exercise
* Work through the Shiny App listed at the end of the assigned DSAIDE book chapter.  


## Quiz

Fill out the quiz sheet for module 3 and submit it. You can find the sheet(s) for this module and submission instructions in the _Course Resources_ section.



###Discussions to participate in
* From the exercise section of the DSAIDE chapter for this module, answer the question that refers to the assigned paper by Kajita et al.
* Post to the discussion forum for this module. The general rules for discussion and assessment apply.

* The Paper by Kajita et al, Nat Rev Mic 2007. When reading the paper, focus on understanding their model and assumptions. You can skim or skip anything related to the reproductive number, R~0~, for now. We'll discuss that quantity soon.


