---
title: Characterizing Infection States 
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r as.Date(file.mtime(knitr::current_input()))`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---


# Overview
In this module, we will discuss how to characterize the infection states of different ID. We will look at this both from a medical perspective and from a public health perspective and discuss how these perspectives complement each other. 


# Learning Objectives

* Accurately categorize infectious diseases according to medical and public health characteristics
* Evaluate the impact of different infection states on medical outcomes and disease dynamics
* Understand how _medical states_ (e.g. symptoms) and _public health states_ (e.g. infectiousness) do not always overlap.
* Identify the features of infectious diseases that are most important to know for successful intervention planning
* Understand how different infections states are represented in mathematical models


# Reading

Read the chapter ["Characterizing Infectious Disease States" of IDEMAB](https://andreashandel.github.io/IDEMAbook/idstates.html). 

The book chapter gives you one introduction to a way of classification individuals with regard to infection and disease states. For some further discussions, watch the following videos. 


# Videos

The first video is from the ["Epidemics"](https://www.coursera.org/learn/epidemics) online course. 

[Mary Poss](https://science.psu.edu/bio/people/mup14), one of the course instructors, talks about the difference between infection and disease.

<p><iframe width="560" height="315" src="https://www.youtube.com/embed/feurlFtWIsM" frameborder="0" allowfullscreen></iframe></p>

The second video is from the [HKU Epidemics course sequence](https://www.edx.org/search?q=epidemics). 

[Joseph Wu](https://sph.hku.hk/en/about-us/faculty-and-staff/academic-staff/wu,-tsz-kei-joseph) from the University of Hong Kong discusses some quantities relating to infection and disease state and duration and their importance for public health. Ignore anything we haven't covered yet.

<p><iframe width="560" height="315" src="https://www.youtube.com/embed/z9EItIxkaVs" frameborder="0" allowfullscreen></iframe></p>



