---
title: IDEMA Course Resources
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r as.Date(file.mtime(knitr::current_input()))`"
output: 
  html_document:
    toc_depth: 3
---


```{r, echo = FALSE}
#just so I can use emoticons
#devtools::install_github("hadley/emo")
library(emo)
```

This page lists resources that are used or mentioned in this course. For a more extensive list of resources, see the _General Resources_ page.

All materials described below are (should be) freely available online. If you can't get to them, let me know. Note that a lot of the listed resources are dynamic and ever changing. That means occasionally links might not work, sites go offline, chapters in online books get re-arranged, etc. If you notice anything that's not quite right, please let me know.

# General help

* The main place to get any course specific help are the various Slack channels in our class workspace. Use them widely to ask questions, to answer others' questions, to post links to interesting resources, etc. 
* There will very likely be times when some material in the course doesn't quite make sense and you need to do some auxiliary reading. Google will be your best friend. Wikipedia is often a very good starting point for many topics. 



# Books

* [Infectious Disease Epidemiology - a Model-based Approach (IDEMAB)](https://andreashandel.github.io/IDEMAbook/). This is the book that goes with the class, it is basically an extended version of my previous lecture notes. It is perpetually under construction and some parts are more polished than others. All chapters assigned in this course should be fairly readable.

# Hands-on/interactive resources

* [Dynamical Systems Approach to Infectious Disease Epidemiology (DSAIDE)](https://ahgroup.github.io/DSAIDE/). The R package for the course which lets you do hands-on explorations of the different topics we will cover.


# Quiz sheets
For each module, you are asked to fill out one or more than one sheets with questions related to the course material. Usually, there is one quiz covering the DSAIDE tasks and one quiz covering the other materials (reading, videos) for a given module (the latter I call _Theory Quiz_ below.)

Each quiz sheet is an Excel file. Download them from the links below, fill in the "Answer" column, and submit to the online grading website.

__Please do not make any other changes to the sheets apart from filling the "Answer" column. If you do make changes, submission might fail. If that happens and you get an error message, simply come back here, download a fresh sheet and copy and paste your answers into it, making sure to not change any other part of the sheet.__


## Module 1 - Course and Topic Introduction
* [Basic SIR DSAIDE Quiz](./quizsheets/dsaide_basicsir.xlsx)
* [Theory Quiz](./quizsheets/theory_basicsir.xlsx)

## Module 2 - Characterizing infection states
* [ID Characteristics DSAIDE Quiz](./quizsheets/dsaide_idcharacteristics.xlsx)
* [Theory Quiz](./quizsheets/theory_idcharacteristics.xlsx)

## Module 3 - Patterns of ID
* [Patterns of ID DSAIDE Quiz](./quizsheets/dsaide_idpatterns.xlsx)
* [Theory Quiz](./quizsheets/theory_idpatterns.xlsx)


## Module 4 - Reproductive Number 1
* [Reproductive number 1 DSAIDE Quiz](./quizsheets/dsaide_reproductivenumber1.xlsx)
* [Theory Quiz](./quizsheets/theory_reproductivenumber1.xlsx)

## Module 5 - Reproductive Number 2
* [Reproductive number 2 DSAIDE Quiz](./quizsheets/dsaide_reproductivenumber2.xlsx)
* [Theory Quiz](./quizsheets/theory_reproductivenumber2.xlsx)

## Module 6 - ID Control 1
* [Basics of ID Control DSAIDE Quiz](./quizsheets/dsaide_idcontrolvaccine.xlsx)
* [ID control for multiple outbreaks DSAIDE Quiz](./quizsheets/dsaide_idcontrolmultioutbreak.xlsx)
* [Theory Quiz](./quizsheets/theory_idcontrol1.xlsx)

## Module 7 - Direct Transmission
* [Direct Transmission DSAIDE Quiz](./quizsheets/dsaide_directtransmission.xlsx)
* [Theory Quiz](./quizsheets/theory_directtransmission.xlsx)

## Module 8 - Environmental Transmission
* [Environmental Transmission DSAIDE Quiz](./quizsheets/dsaide_environmentaltransmission.xlsx)
* [Theory Quiz](./quizsheets/theory_environmentaltransmission.xlsx)

## Module 9 - Vectorborne Transmission
* [Vectorborne Transmission DSAIDE Quiz](./quizsheets/dsaide_vectortransmission.xlsx)
* [Theory Quiz](./quizsheets/theory_vectortransmission.xlsx)

## Module 10 - Host Heterogeneity
* [ Host Heterogeneity DSAIDE Quiz](./quizsheets/dsaide_hostheterogeneity.xlsx)
* [Theory Quiz](./quizsheets/theory_hostheterogeneity.xlsx)

## Module 11 - ID Control 2
* [ID Control of different populations DSAIDE Quiz](./quizsheets/dsaide_idcontrolmultigroup.xlsx)
* [Complex ID control scenarios DSAIDE Quiz](./quizsheets/dsaide_idcontrolcomplex.xlsx)
* [Theory Quiz](./quizsheets/theory_idcontrol2.xlsx)

## Module 12 - Stochasticity
* [Stochastic SIR Model DSAIDE Quiz](./quizsheets/dsaide_stochasticsir.xlsx)
* [Stochastic SEIR Model DSAIDE Quiz](./quizsheets/dsaide_stochasticseir.xlsx)
* [Theory Quiz](./quizsheets/theory_stochasticity.xlsx)

## Module 13 - Evolutionary Dynamics
* [Evolution of Drug Resistance DSAIDE Quiz](./quizsheets/dsaide_evolution.xlsx)
* [Theory Quiz](./quizsheets/theory_evolution.xlsx)

<!-- comment out quizzes that are not ready yet

-->

_Further quizzes will show up here as the course progresses._

# Exercise solutions

After the due date for each quiz, I will place solution files to the DSAIDE exercises in a Dropbox folder. They are fairly detailed and also show you how you can use `R` commands (instead of the graphical interface) to do all the Tasks. I highly recommend looking at them (even if you get all answers correct). The link to the dropbox folder is pinned in the _Announcement_ channel on Slack.

