---
title: Module 1 Assessment 
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r as.Date(file.mtime(knitr::current_input()))`"
output: 
  html_document:
    toc_depth: 3
---

# Module Assessments

The following items will be assessed for this module.


## Quizzes

* There is a quiz sheet that goes with the _Basic SIR_ DSAIDE app. Work through the app, fill out the sheet and submit as described in the  _Exercises_ document of this module.
* There is a second quiz sheet which covers some of the material (reading and videos). For this module, it is very short and mostly meant to get you into the rhythm of things and to help me work out any kinks in the submission system. Fill out this quiz and submit like the DSAIDE app. The order of submission does not matter.


## Exercises

* Do the introduction exercise as described in the  _Exercises_ document of this module. Post your own and reply to others' posts.
* Do the discussion post as described in the  _Exercises_ document of this module. Post your own and reply to others' posts.
