---
title: General Infectious Disease Epidemiology and Modeling Resources
author:
  - name: "Andreas Handel"
    url: https://www.andreashandel.com/
date: "`r as.Date(file.mtime(knitr::current_input()))`"
bibliography: ./media/references.bib
output: 
  html_document:
    toc_depth: 3
---


```{r, echo = FALSE}
#just so I can use emoticons
#devtools::install_github("hadley/emo")
library(emo)
```

To distinguish between resources that are used in the course, and others that are related but not directly used, I decided to have two resource pages. The _Course Resources_ page lists materials we'll be (partially) using in the course. This page lists a lot of other resources that might not be used or mentioned explicitly in the course, but that might be useful and interesting. For even more materials, see the links to various lists by others at the end of this document.

Apart from the books, most other materials described below are (should be) freely available online. Some of the resources I list are dynamic and ever changing. That means occasionally links might not work, sites go offline, chapters in online books get re-arranged, etc. If any link does not work and you can't access the materials for some reason, let me know so I can update this document.

_Obviously, there is no way my list is exhaustive. Let me know if you find other relevant and good sources._

# Books


## Infectious Disease Epidemiology

* Giesecke, Johan. 2017. Modern Infectious Disease Epidemiology. CRC Press.
* Nelson, Kenrad E, and Carolyn Williams. 2013. Infectious Disease Epidemiology. Jones & Bartlett Publishers.

## General modeling
* Britton (2003) Essential mathematical biology. Springer: Relatively easy, not too math heavy.
* Allman and Rhodes (2004) Mathematical Models in Biology: An Introduction. Cambridge U Press: Integrates MATLAB into the text/exercises.
* Ellner and Guckenheimer (2006) Dynamic Models in Biology. Princeton University Press: Nice integration of mathematical analysis and computer modeling, topics very broad.
* Otto and Day (2007) A Biologist's Guide to Mathematical Modeling in Ecology and Evolution. Princeton University Press: Some good background/primers on
math topics, explanations on how to model, not much infectious disease specific material.

## Infectious disease modeling books

__Approximately sorted in order of difficulty (according to my opinion)__

* [An introduction to infectious disease modeling by Emilia Vynnycky and Richard White](http://www.anintroductiontoinfectiousdiseasemodelling.com/). The most introductory level book.
* [Modeling Infectious Diseases in Humans and Animals by Matt J. Keeling & Pejman Rohani](http://www.modelinginfectiousdiseases.org/). Introductory but at a higher level.  
* Bjornstadt (2018) Epidemics - Models and Data using R. Shows how to do it in R. Some topics are basic, others fairly advanced and theoretical.
* Anderson and May (1992) Infectious Diseases of Humans - Dynamics and ControL. The "classic". Lots of material, but the math can be somewhat challenging. 
* Daley and Gani (2001) Epidemic modeling: an introduction. Thorough mathematical treatment, not too intuitive/easy.
* Diekmann & Heesterbeek (2000) Mathematical Epidemiology of Infectious Diseases: Model Building, Analysis and Interpretation. Relatively advanced math level.


# Papers

## Population level modeling papers
* Ness et al. “Causal System Modeling in Chronic Disease Epidemiology: A Proposal” (2007) Ann Epidemiol
* Sterman “Learning from Evidence in a Complex World” (2006) PHM
* Kajita et al. (2007) Nature Reviews Microbiology
* Grassly & Fraser (2008) Nature Reviews Microbiology
* Brauer (2009) BMC Public Health
* Wendelboe et al. (2010) Am J Med Sci
* Louz et al. (2010) Critical Reviews in Microbiology
* Garnett et al. (2011) Lancet
* Epstein “Why Model?”
* May “Uses and Abuses of Mathematics in Biology” (2004) Science


# Online courses

Throughout this course, I link to videos from a few online courses that cover similar topics to this course. While the videos are embedded and you do not need to sign up for those online courses, if you are interested, you could. Signing up for those courses should be free. Coursera might want to talk you into getting a certificate (and paying), but you can skip that and get the whole course content for free (last time I checked, let me know if that has changed.)

* [Epidemics](https://www.coursera.org/learn/epidemics). This course was developed by several infectious disease faculty at Penn State and is offered through the MOOC provider Coursera. There is also [an accompaning webpage with interesting ID related resources](http://epidemics.psu.edu/).
* [Epidemics](https://www.coursera.org/learn/hkuepidemics/). This course has the same name and lives on the same platform as the Penn State course, but it is offered by a team of instructors from the University of Hong Kong (HKU).

Note that the HKU course started out as a course called "Epidemics" on the EdX platform. Now there is the above course on the Coursera platform. In addition, there is a sequence of courses, [Epidemics I-IV on the EdX platform](https://www.edx.org/search?q=epidemics). The Coursera and EdX offerings seem similar, I don't know if/how they differ.

For this class, I will embed all relevant materials. You therefore don't need to further check out those courses if you don't want to. However, if you are interested, I encourage you to give them a try. They have great content and cover some topics which we won't cover in this course. Neither of these courses takes an explicit model-based perspective, but many topics are discussed with such a framework in mind (and several of the instructors for each course are infectious disease modelers).

* [Model fitting and inference for infectious disease dynamics](http://sbfnk.github.io/mfiidd/index.html). Materials for an online course . This is rather advanced material.




# Software

* [idmodelr](https://www.samabbott.co.uk/idmodelr/) by Sam Abbott. Many basic compartmental (SIR type) models, a little bit of coding is required. He also has [a list of related resources](https://www.samabbott.co.uk/idmodelr/articles/resources.html), which - not surprisingly - has a lot of overlap with the information on this page.

* [shinySIR](https://github.com/SineadMorris/shinySIR) by Sinead Morris. Exploration of several SIR-type models through Shiny. It doesn't have the detailed documentation of [DSAIDE](https://ahgroup.github.io/DSAIDE/), but it includes some models not in DSAIDE.

*  [The R Epidemics Consortium](https://reconhub.github.io/) maintains several R packages related to infectious disease modeling. Most of the content is oriented toward researchers/practitioners, but there is also some teaching/learning material.

* [Epimodel](https://www.epimodel.org/) is a website for the R package(s) of the same name that allow fairly user-friendly building and exploring of ID Epi models. The strength of Epimodel and related packages (the [Statnet suite of R packages](http://statnet.org/)) is in network based models.

*  [The pomp R package to fit stochastic dynamic models (and more) to time-series data.](http://kingaa.github.io/pomp/) This is a powerful package and the package contains a good bit of tutorials and information. It is overall fairly advanced material.
   
   


# ID epi and modeling websites

* [NRICH project on infectious disease dynamics](https://nrich.maths.org/epidemic). A nice collection of resources and activities related to infectious disease epidemiology from a mathematical and modeling angle. The target age group are teenagers, but the material is likely suitable for older ages too. This is mainly meant for teachers to implement, but can also be useful for self-learning.
* [The Epirecipes site](http://epirecip.es/) contains a _cookbook_ of many standard infectious disease models with code in several different programming languages (including R).




