---
title: Overview of Infectious Disease Dynamics  
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r as.Date(file.mtime(knitr::current_input()))`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---



##Overview
This module provides an introduction to the overall idea of studying the dynamics of infectious diseases, why it is useful to take a model-based approach, and what that means. 


# Assignments

Start by reading the chapter ["Introduction to the dynamical systems approach" of IDEMAB](https://andreashandel.github.io/IDEMAbook). 


* The paper "Systems Science Methods in Public Health: Dynamics, Networks, and Agents" by Luke & Stamatakis (in the folder for this module).

For some further discussions, check out the following videos. 


_Note: For this and any future modules, you can do the videos and readings in any order. Usually, if there is a paper assigned, it is best to read it last since it often assumes knowledge of material covered in the videos and the reading._

###Computer Exercises to do
* Work through the Shiny App listed at the end of the assigned DSAIDE book chapter, i.e. read the information on all tabs inside the app and do all tasks described in the "What to do" section. 

__As you work through the apps, always take notes, write down your results as you work through the shiny app. The practice quiz for this module (and all others) will ask you about specific results you got by doing the Shiny app exercises.__ (E.g. you might be asked 'What was the number of susceptibles left at the end of the outbreak for task 3 in the shiny app for this module?').  

###Discussions to participate in
* From the exercise section of the DSAIDE book chapter for this module, answer the question that refers to the assigned paper by Luke & Stamatakis. 
* Post your answer to the exercise to the discussion forum for this module. Then comment on posts by others. The general rules for discussion and assessment as described in the first module apply.

_In addition to the tasks just described, you are welcome and encouraged to discuss anything else related to the content of this module within the topic for this module. Discuss anything else relevant to the course in the appropriate topic area._


##Introduction Video
In this video, I provide a brief introduction to the concept of dynamical systems thinking applied to infectious diseases

<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/t5D5ki18cO8" frameborder="0" allowfullscreen></iframe>
</p>


##Systems Thinking
This video provides a nice introduction to systems thinking, using the example of obesity.
<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/2vojPksdbtI" frameborder="0" allowfullscreen></iframe>
</p>


## A systems model example
A famous dynamical system model (not from the area of infectious diseases) is Schelling's segregation model. In the following video, [Scott Page](http://sites.lsa.umich.edu/scottepage/) explains and illustrates this model.  
<p> 
<iframe width="560" height="315" src="https://www.youtube.com/embed/dFl3Cfw12bo" frameborder="0" allowfullscreen></iframe>
</p>
This video is part of a course called ["Model Thinking"](https://www.coursera.org/learn/model-thinking). Like all Coursera courses, it is available for free. I highly recommend the course.


## Models in infectious disease epidemiology
This video is from a MOOC (Massive Open Online Course) called ["Epidemics"](https://www.coursera.org/learn/epidemics), developed by several infectious disease faculty at Penn State and offered through the MOOC provider Coursera. Matt Ferrari, one of the course instructors, gives a brief discussion of infectious disease models.
<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/SmhgeS-g90c" frameborder="0" allowfullscreen></iframe>
</p>





