---
title: Patterns of infectious diseases 
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r as.Date(file.mtime(knitr::current_input()))`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---


# Overview
In this module, we will discuss different patterns of ID dynamics, such as single outbreaks, recurrent cycles, and steady endemic states. 



# Learning Objectives

* Understand the concept of resource replenishment
* Know the different mechanisms that can lead to ID cycles
* Understand the concept of endemic state
* Understand what leads to different ID patterns
* Understand the difference between intrinsic and extrinsic drivers of ID cycles



# Reading

Read ["Patterns of ID dynamcis"](https://andreashandel.github.io/IDEMAbook/patterns-of-infectious-disease-dynamics.html) of IDEMAB.


# Videos

The following videos provide complementary material and cover some aspects concerning different general patterns of ID dynamics, and what conditions can lead to different outcomes, such as single outbreaks, repeated outbreaks/cycles, and steady endemic states.

In these two videos from the ["Epidemics MOOC"](https://www.coursera.org/learn/epidemics), 
[Ottar Bjornstad](https://ento.psu.edu/directory/onb1) discusses cycles of ID dynamics and the impact of seasonality.

<p><iframe width="560" height="315" src="https://www.youtube.com/embed/Mf_EZm5amxI" frameborder="0" allowfullscreen></iframe></p>

<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/TDuuM-wm6nw" frameborder="0" allowfullscreen></iframe>
</p>


