---
title: Project Review Information 
author: Andreas Handel
institute: "University of Georgia"
date: "`r as.Date(file.mtime(knitr::current_input()))`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---

# Overview

After the project has been completed, each of you will review the projects of several of your classmates, similar to peer-review of a manuscript submitted for publication. The goals for this project review are:

* You get feedback that helps you improve your project.
* You get experience with giving and receiving reviewer feedback, like you would when you submit a paper for publication or review someone's submitted paper.


# Logistics
* The last week of the class (after thanksgiving) is devoted to peer review of class projects.
* By the __part 4 due date__ specified in the _Schedule_ document, everyone needs to have finished their project and posted either the project file or a link to the file on Slack. If your project consists of multiple files, I recommend either posting a zip file to Slack or a link to some online location where the files can be downloaded.
* Check the Slack projects channel for information on the projects you are assigned to review. Obtain those projects (you are of course welcome to look at other projects too).


* Follow their provided instructions to reproduce everything. Review the whole project using [this review template](./media/Project_Review_Template.Rmd).
* Write up a detailed review using and filling out the template Markdown file. Once you are done, send a pull request for each project you review, containing your completed review document.



# Review Assessment Rubric
Ok, now it gets maybe a bit complicated. I will review and assess the quality of your reviews. To that end, I'll use a fairly simple rubric, similar to the ones for the previous project submissions.

| **Category** | **Description**  | **Score** |
| --- | --- | --- |
| Absent | No reviews were submitted | 0 |
| Insufficient | Only one review was submitted, or submissions were very incomplete | 50 |
| Not fully sufficient | Reviews are somewhat incomplete, lack useful/detailed feedback | 75 |
| Sufficient | Reviews are complete or fairly complete | 100 |


# Finals steps
* Use the feedback/reviews you get to further improve your project.
* Push your final project to your GitHub repository by the specified deadline for final grading.
* I will assess your final project using the same categories in the template used during peer review.