---
title: IDEMA Course Project Examples 
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r as.Date(file.mtime(knitr::current_input()))`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---

# Overview

To showcase some of the work previous students have done, and as inspiration of future projects, below you can find links to a selection of past projects. 

(The reason not many projects for early years are shown is because I wanted to only post projects with student permission and I decided to post this in 2020 and it was hard to reach long-graduated students (and enrollment in previous years was smaller) `r emo::ji('smile')`). 

# 2020 Projects

* [The Little Things that Make Up Our World, How They Spread and How to Control Them](https://ed.ted.com/on/3RcRFTdu) - A TedEd lesson by Kayla Adcock.
* [Pertussis Resurgence and Waning Immunity](https://ed.ted.com/on/jQ8yORTf) - A TedEd lesson by Saige Armistead, Amanda Caulfield and Alexis Cheffen.
* [What is HIV and how can it spread in a population](https://ed.ted.com/on/SB3Q6tMr) - A TedEd lesson by Danielle Armstrong, Morgan McMahan, and Rochelle Obiekwe.
* [A COVID-19 outbreak scenario case study](https://outbreakscenario.wordpress.com/) - an interactive case study game by Rachel Baugh and Dionne Mitcham. 
* [COVID 19 - Escape Infection](https://docs.google.com/presentation/d/1xoRyDp_kpG5Gp3gGzWI7q8P4vm2nFH8YXo6eDMaeZHY/preview#slide=id.g539b68e07a_1_31) - a choose your own adventure storybook by Charisma Atkins, Maureen Bartee, Zena Belay and George Vaughan. 
* [Time trends of COVID 19 cases and public interest](./media/Jennifer_Roberts_Class_Project_2020.pdf) - a data analysis by Jennifer Roberts.
* [A Review of Hospital-Acquired Methicillin-resistant Staphylococcus aureus (HA-MRSA) and the Mathematical Models Estimating the Reproductive Number](./media/MRSA_and_R0_2020_Project.pdf) - a systematic review by Michelle Bentivegna and Cassie Hulme.


# 2017 Projects

* [Using structured decision-making to manage an infectious disease outbreak: an influenza case study tutorial](./media/2017_Final_Project_Cheng.pdf) - a research and policy analysis project by Ellen Cheng. [R/Shiny code for the project.](./media/2017_Final_Project_Cheng_app.R)
* [Spatial Metapopulation Modeling of Infectious Disease Dynamics](./media/2017_Final_Project_Dailey.html) - a project in the style of a potential DSAIDE app by Cody Dailey. [Project code files are in this zip folder.](./media/2017_Final_Project_Dailey.zip)
* [Modelling the Prevalence of Infectious Diseases with Mosquito Vectors when Affected
by Climate Change](./media/2017_Final_Project_Ali_Roles.pdf) - a research project and DSAIDE app by Eliza Ali and Lindsey Roles. [Project code files are in this zip folder.](./media/2017_Final_Project_Ali_Roles.zip)


# 2016 Projects

* [Assessment of Current Human Papillomavirus Dynamic Vaccination Modelling Strategies](./media/2016_Final_Project_McKay_Perry.pdf) - a research project by Brian McKay and Ariella Perry (now Dale).
