---
title: IDEMA Course Project Information 
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r as.Date(file.mtime(knitr::current_input()))`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---

# Overview

Part of the assessment for this class is a semester-long project, broken into different parts. The project content is fairly flexible, as long as it covers some infectious disease topic relevant to the course.

This document contains the information you need to do the class project. If you still have questions after going through this document, post them in the _Class Project_ channel. Also, use that channel for anything related to the project.


# Project Requirements

Broadly speaking, anything that falls within the overall infectious disease topic covered in this course is acceptable as the class project. Your project should have a model/systems perspective, but does not need to make explicit use of models. You are welcome to come up with your own project idea. The final product must at least involve a written report of some form. Beyond that, you can create other products (websites, videos, games, etc.). 

One of the most important components of any project is to find a topic and question that is is new and hasn't been done yet, is interesting and thus worth doing, and is of the right size: not too small to be uninteresting, but prescribed enough enough to be feasible withing the given constraints (i.e. here doable as a class project in one semester). 

__Done well, your project could potentially lead to a product that can go beyond satisfying the course requirement (e.g. a published paper, a new DSAIDE app, a published Ted Ed lesson). Getting to that stage is not required for the class, but being able to turn the project into something that 'counts in the real world' (i.e. something you can add to your CV/portfolio) might be motivating and thus worth pursuing. If you want to pursue this, I'm happy to provide help beyond the class if needed.__


# Project Ideas
The following are some ideas for projects I was able to come up with. You don't have to pick any of these ideas. They are mainly meant to get you thinking about suitable types of projects.


## Research type projects

_A project of this type should lead to a - possibly publishable - manuscript-type report. Structure and formatting should follow general manuscript style, the details are up to you._

* Pick an ID epi topic and write a paper on it. This could take the form of a review or opinion paper. You'll see several of those types of papers throughout the course. Here are a few examples some of which we'll be reading at some point during the course: [Martinez 2018 PLoS Pathogens](https://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1007327), [Alizon and Methot 2018 PLoS Bio](https://doi.org/10.1371/journal.pbio.2003815), [Beldomenico and Begon 2009 TREE](./media/references/beldomenico09tree.pdf), [Simonsen et al 2007 Lancet ID](./media/simonsen07lancetid.pdf). 

* Use one of the apps in the DSAIDE package - potentially supplemented with some of your own code - to answer a new and interesting question related to a specific ID. Pick an ID, describe what you plan on analyzing, use the appropriate DSAIDE app (either through the graphical interface or the "Level 2/3 approach") to answer your question. The research question should be realistic in scope, interesting, and one that hasn't been asked before. Alternatively, you can build your own model and analyze it without having to write code using [the modelbuilder R package](https://ahgroup.github.io/modelbuilder/). Other software can also be used that doesn't require coding (e.g. Berkeley Madonna, Numerus Model Builder). This is basically a straight 'modeling research paper'. It goes a bit beyond the course since you would have to do some active model building/use, but some of you might be up to it. Here is an example, one of my past projects, of a paper that uses a very simple model: [Handel 2007 PRSB](https://royalsocietypublishing.org/doi/10.1098/rspb.2006.0015). Here is another example of a recent, fairly simple model applied to COVID-19: [Weitz et al 2020 Nat Med](./media/weitz20natmed.pdf).

* Find some publicly available data related to ID Epidemiology (e.g. see [this list](https://andreashandel.github.io/research-and-teaching-resources/Data_Resources.html) or any other source) to investigate an interesting question. The analysis does not have to involve the kind of simulation models we are using in the class, though you'll likely be doing some statistical data analysis. Thus, this will be somewhat beyond the content covered in this class. But several of you will already have the necessary skills. Examples of this type: [Arehart et al 2019 Sci Rep](https://www.nature.com/articles/s41598-019-56385-z), [Lopman et al 2003 EID](./media/lopman03eid.pdf), [Simonsen et al 2005 JAMA IM](https://jamanetwork.com/journals/jamainternalmedicine/article-abstract/486407).

* Use [US News Map](http://usnewsmap.com/) to look at the spread of the term/word 'influenza' (and related terms) during the 1918 pandemic, then look at the spread of information (i.e. the word influenza and related) during the 2009 pandemic (e.g. using [Google Trends](https://trends.google.com)) or other sources. Compare that with actual incidence data for those 2 outbreaks. It would be interesting to see if the pace of either information dissemination or the disease spread itself differed. A variation of this could be to compare other major outbreaks, e.g. COVID-19 and the 1918 or 2009 influenza pandemics or some other prior outbreak.



## Teaching/outreach type projects

_A project of this type should lead to a (potentially brief) report describing the overall project, and in addition to some other product (website/video/app/etc.). The latter might be "publishable"._ 

* Pick some ID topic and come up with a concept for a [TED Ed lesson](http://ed.ted.com/). For ideas, check out some of the ID examples on the TED Ed website, e.g. [this one](https://ed.ted.com/lessons/how-do-germs-spread-and-why-do-they-make-us-sick-yannay-khaikin-and-nicole-mideo) or [this one](https://ed.ted.com/lessons/when-is-a-pandemic-over). Produce a concept book/script/detailed outline of your lesson. Design a quiz and a 'further resources' page (the 'think' and 'dig deeper' sections of a TED Ed lesson). If you feel up to it, take a stab at recording a video.   

* Pick an ID topic (that we did or did not cover in class) for which there is currently no DSAIDE app. Create a new app for DSAIDE that allows users to explore the topic. App development requires some R coding skills, though the most critical part for this project is to have a good topic and strong documentation (mainly _Model_ and _Tasks_ sections) that nicely teach the topic. If you plan on doing this, let me know and I will help you get started and give you further details on how this is best done. For examples, look at the _Further ID Topics_ section in DSAIDE, several of those were contributed by students.

* Pick some ID topic and come up with an idea for an (online) game illustrating the topic. (For inspiration, check out http://vaxpackhero.com and http://vax.herokuapp.com/). Write a report that describes in detail your game idea. It should be a document one could give to a software/app developer who would then build the game. If you feel bold and have the necessary coding skills, you are welcome to try and develop the game (or at least a prototype). That can be written in a programming language of your choice - it doesn't have to be R.

**To reiterate, these topics are examples of what you can do. You can choose to do something different as long as it is infectious disease epidemiology related and has some kind of systems/model component.**


# Project Logistics
You can do the projects in teams, up to a maximum of 4 individuals per team. If you rather do it by yourself, that's ok too. Anywhere between 1-4 individuals per project is ok. Always list all team members on any project submission. You can find teams and bounce around ideas using the _Class Project_ Slack channel. 

Before/by each of the deadlines for the different project parts (for dates, see the _Schedule_ document), submit your results or a link to your results to the _Class Project_ Slack channel. If your project consists of multiple files, I recommend either posting a zip file to Slack or a link to some online location (e.g. Dropbox or OneDrive) where the files can be downloaded.

Your final report should look and read like a nicely formatted research paper or a technical report. Include references as usual. Figures and tables should be included at the appropriate places inside the text (not at the end). Look at regular published papers/reports to see examples of formatting. Any additional deliverables (e.g. website, software, videos, etc.) should be supplied as supplementary files, or provided as links. 


# Timeline
There are several deadlines throughout the course at which time you need to submit parts of your project

* Part 1: Have a project idea. You need to have picked a topic and written a short plan/proposal describing your topic, project, approach and expected outcomes. 
* Part 2: Overall outline for project, with some content starting to be filled in. 
* Part 3: First version of project with most content in place, at least in draft form. You don't need to have everything completed, but the main outline of your report and deliverables need to be there and filled with whatever you have done up to that point. 
* Part 4: Complete project, ready for peer review.
* Part 5: Complete project, updated based on reviewer feedback, ready for final assessment.

The deadlines are listed in the _Schedule_ document (it's unlikely, but they might change, so keep checking that document).


# Feedback and Assessment
You will receive feedback from me and/or your classmates after each submission. 

* I will provide feedback on parts 1-3. 
* Your classmates will provide peer-review for part 4.
* Part 5 is the final submission. 

I will assess parts 1-3, mainly checking to see that you deliver what you were supposed to and got the project to the requested stage. I will also assess your _peer reviews_ for part 4. Those portions are 40% of the _project grade._ The final submission will count for the remaining 60%. 

**More details on what exactly is expected and how it is assessed is provided in the _Project Rubric_ document.**

# Project communications 
Any general communication and asking of questions regarding this project should happen in the _Class Project_ channel. Go there to ask project-specific questions, to post links to your documents whenever you have a part finished, etc. I will also post any further or clarifying information there. Of course, beyond that you are welcome to communicate with your project group members in any other way you like.
