---
title: Reproductive Number 1 
author: Andreas Handel
date: "`r as.Date(file.mtime(knitr::current_input()))`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---


# Overview
In this module, we will start our discussion of an important concept in infectious disease epidemiology, the reproductive number. We will define it and discuss why it is a very important quantity in infectious disease epidemiology. We will discuss what the reproductive number does and does not tell us about the dynamics of an outbreak, and how to estimate it for a given disease.


# Reading

Start by reading the ["Reproductive Number" chapter of IDEMAB](https://andreashandel.github.io/IDEMAbook/R0.html). 
We'll cover the material in two sessions, but I suggest you read the whole chapter this week, and then once more next week, after you've worked through the first DSAIDE exercise.


# Videos

For some complementary discussions of the reproductive number, check out the following videos. 

## Contagion Video Clip
The reproductive number is such an important concept in infectious disease epidemiology. It has even found its way into mainstream media. The following video is a short clip from the 2011 movie ["Contagion"](http://en.wikipedia.org/wiki/Contagion_%28film%29). In the movie, Kate Winslet plays an Epidemic Intelligence Service (EIS) officer, who is sent to help the local state health department study the spread of a new, somewhat deadly disease. In this short excerpt, she meets with the leaders of the state health department for an initial discussion. The reproductive number is part of the discussion.

<p><iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/1727411/sp/172741100/embedIframeJs/uiconf_id/23856721/partner_id/1727411?iframeembed=true&amp;playerId=kaltura_player&amp;entry_id=1_ifdbz5n7&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;&amp;wid=1_c2h6vrdc" allowfullscreen="" webkitallowfullscreen="" mozallowfullscreen="" frameborder="0" height="285" width="400"></iframe></p>


Note that she gets some details wrong. Pay close attention. (Whoever advised on the Science was apparently not an Infectious Disease Epidemiologist.)

The outbreak in the _Contagion_ movie has a lot of similarities to COVID-19! Fortunately, COVID-19 is not as deadly. Unfortunately, politicians and the overall leadership seem more competent in the movie than in real life.



## A more detailed explanation of the reproductive number
This video is from a MOOC (Massive Open Online Course) called ["Epidemics"](https://www.coursera.org/learn/epidemics), developed by several infectious disease faculty at Penn State and offered through the MOOC provider Coursera. 

[Matt Ferrari](https://theferrarilab.squarespace.com/) provides a very good explanation of the reproductive number concept.

<p><iframe width="560" height="315" src="https://www.youtube.com/embed/ju26rvzfFg4" frameborder="0" allowfullscreen></iframe></p>


## Reproductive number and epidemic curve
This is another video from the ["Epidemics MOOC"](https://www.coursera.org/learn/epidemics). 

[Ottar Bjornstad](https://ento.psu.edu/directory/onb1), one of the course instructors, discusses the shape of an individual outbreak curve and how it relates to the reproductive number.

<p><iframe width="560" height="315" src="https://www.youtube.com/embed/sSLfrSSmJZM" frameborder="0" allowfullscreen></iframe></p>

